version: '3.5'

services: 
  homeapp:
    container_name: homeapp_container
    build:
      context: ./services/homeapp
      dockerfile: Dockerfile-django
    volumes:
      - './services/homeapp:/usr/src/app'
    ports:
      - '8000:8000'
    depends_on:
      - homeapp_db
  
  homeapp_db: # new
    build:
      context: ./services/db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
